export default {
    "backspace": "backspace",
    "delete": "delete",
    "enter": "enter",
    "tab": "tab",
    "escape": "escape",
    "capslock": "capslock",
    "space": "space",
    "printscreen": "printscreen",
    "menu": "menu",
    "navigation": {
        "up": "up",
        "down": "down",
        "right": "right",
        "left": "left",
        "home": "home",
        "end": "end",
        "pageup": "pageup",
        "pagedown": "pagedown",
        "insert": "insert"
    },
    "function": {
        "f1": "f1",
        "f2": "f2",
        "f3": "f3",
        "f4": "f4",
        "f5": "f5",
        "f6": "f6",
        "f7": "f7",
        "f8": "f8",
        "f9": "f9",
        "f10": "f10",
        "f11": "f11",
        "f12": "f12"
    },
    "modifiers": {
        "winkey": "command",
        "alt": "alt",
        "rightAlt": "right_alt",
        "control": "control",
        "leftControl": "left_control",
        "rightControl": "right_control",
        "shift": "shift",
        "rightShift": "right_shift"
    },
    "audio": {
        "mute": "audio_mute",
        "volumeDown": "audio_vol_down",
        "volumeUp": "audio_vol_up",
        "play": "audio_play",
        "stop": "audio_stop",
        "pause": "audio_pause",
        "prev": "audio_prev",
        "next": "audio_next"
    },
    "numpad": {
        "numLock": "numpad_lock",
        "0": "numpad_0",
        "1": "numpad_1",
        "2": "numpad_2",
        "3": "numpad_3",
        "4": "numpad_4",
        "5": "numpad_5",
        "6": "numpad_6",
        "7": "numpad_7",
        "8": "numpad_8",
        "9": "numpad_9",
        "plus": "numpad_+",
        "minus": "numpad_-",
        "star": "numpad_*",
        "forwardSlash": "numpad_/",
        "dot": "numpad_."
    }
};
